import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Bot, X, Lightbulb, ArrowRight, Workflow, HelpCircle } from 'lucide-react'
import type { ViewId } from './Sidebar'

interface AIAssistantProps {
  activeView: ViewId
  problemConfig?: any
}

const VIEW_HELP: Record<ViewId, { title: string; explanation: string; tips: string[]; nextStep?: { label: string; view: ViewId } }> = {
  home: {
    title: 'Welcome to GFlowNet Optimization Lab',
    explanation:
      'This is your launchpad. GFlowNet (Generative Flow Network) is a method for sampling diverse, high-reward objects proportionally to a reward function. ' +
      'Unlike RL which finds a single optimum, GFlowNet discovers a diverse set of candidates — ideal for drug discovery, material science, and combinatorial optimization.\n\n' +
      'Start by understanding the framework (Formulate) or jump straight to configuring an experiment.',
    tips: [
      'New to GFlowNet? Start with "Formulate" to understand the framework',
      'Grid World is the best starting point to learn GFlowNet fundamentals',
      'Molecular Design uses fragment-based construction with 50 fragments',
      'All training objectives (TB, STB, DB, FM, TLM) are supported across domains',
    ],
    nextStep: { label: 'Formulate your problem', view: 'formulate' },
  },
  formulate: {
    title: 'Formulate Your GFlowNet Problem',
    explanation:
      'Every GFlowNet problem requires four components:\n\n' +
      '1. State Space (S) — All possible partial and complete objects\n' +
      '2. Action Space (A) — Transitions that build objects step-by-step\n' +
      '3. Reward Function R(x) — Scores terminal states; GFlowNet samples x ∝ R(x)\n' +
      '4. Training Objective — Loss enforcing flow conservation (TB, DB, STB, FM, TLM)\n\n' +
      'This page helps you understand these components across different domains. Pick a template to start, or define your own.',
    tips: [
      'Molecular generation is ONE application — GFlowNet works on any discrete DAG structure',
      'Grid World is ideal for testing ideas before scaling to complex domains',
      'TB (Trajectory Balance) is the most robust objective for beginners',
      'The reward function is the most important design choice — spend time here',
    ],
    nextStep: { label: 'Configure your experiment', view: 'configure' },
  },
  configure: {
    title: 'Configure Experiment',
    explanation:
      'Set up your GFlowNet experiment in 3 steps:\n\n' +
      '1. Domain — Choose your problem space (grid, molecule, DAG, sequence, custom)\n' +
      '2. Parameters — Set domain-specific parameters (grid size, fragment constraints, etc.)\n' +
      '3. Training — Set training hyperparameters (objective, episodes, LR, exploration)\n\n' +
      'The training objective controls how the flow network learns. Mode collapse prevention (epsilon, entropy, replay) helps discover diverse solutions.',
    tips: [
      'TB objective is recommended for beginners — robust and well-studied',
      'Enable epsilon exploration (15%) with decay for better diversity',
      'For molecules: use hidden_dim=256, LR=0.001, batch=16',
      'For grid worlds: use hidden_dim=64, LR=0.005, batch=32',
    ],
    nextStep: { label: 'Start training', view: 'train' },
  },
  train: {
    title: 'Training Monitor',
    explanation:
      'This dashboard shows your GFlowNet training in real-time.\n\n' +
      '• Loss — Should decrease over time; measures how well flow constraints are satisfied\n' +
      '• Reward — Mean reward of generated samples; should increase\n' +
      '• Gradient Norm — Training stability indicator; spikes may indicate instability\n' +
      '• Epsilon — Exploration rate; decays over time if decay is enabled\n\n' +
      'For molecular domain, the live feed shows recently generated candidates.',
    tips: [
      'Loss not decreasing? Try lowering the learning rate or increasing batch size',
      'Low diversity? Increase epsilon or entropy weight',
      'You can extend training or retrain with different hyperparameters',
      'Pause training to inspect intermediate results without stopping the session',
    ],
  },
  candidates: {
    title: 'Candidates / Results',
    explanation:
      'Browse all solutions generated by your GFlowNet training.\n\n' +
      'Candidates are ranked by reward score. Data comes from both the current training session (in-memory) and the persistent database that stores all historical results.\n\n' +
      'For molecular domain: filter by MW, LogP, QED, SA. For grid world: sort by position reward.',
    tips: [
      'Sort by different properties to explore the solution landscape',
      'Select candidates to export as SMILES, SDF, CSV, or JSON',
      'High reward doesn\'t always mean best — check diversity too',
      'Click a candidate to view its structure in the Structure viewer',
    ],
    nextStep: { label: 'Inspect structures', view: 'structure' },
  },
  toolkit: {
    title: 'Molecular Design Toolkit',
    explanation:
      'A unified hub for all molecular design capabilities.\n\n' +
      '• Diversity — Tanimoto similarity matrix, IntDiv metrics, scaffold analysis\n' +
      '• Docking — Binding affinity prediction with AutoDock Vina proxy\n' +
      '• Fragments — Browse the BRICS fragment library (50 fragments, 4 categories)\n' +
      '• Synthesis — Reaction-constrained generation with 17 SMARTS templates\n' +
      '• Pareto — Multi-objective optimization with preference-conditioned sampling',
    tips: [
      'Run a molecular training session first to populate diversity and docking data',
      'Fragment Browser works without training — explore the building blocks anytime',
      'Use Pareto tab to balance QED, SA, LogP, and docking objectives simultaneously',
      'Synthesis routes ensure generated molecules are practically synthesizable',
    ],
    nextStep: { label: 'Inspect structures', view: 'structure' },
  },
  structure: {
    title: 'Structure Viewer',
    explanation:
      'Inspect the detailed structure of generated candidates.\n\n' +
      'For molecules: 3D conformations from SMILES using RDKit distance geometry. ' +
      'For grid worlds: step-by-step path visualization from origin to terminal state. ' +
      'For DAGs: generated sub-graph with highlighted edges.\n\n' +
      'The viewer adapts to your domain automatically.',
    tips: [
      'Molecules: Ball & Stick mode shows bond connectivity, Surface mode shows molecular envelope',
      'Grid: overlay the reward landscape to see where the path lands',
      'Color by reward to visually compare candidates',
      'Toggle between top-N candidates using the navigation controls',
    ],
  },
  landscape: {
    title: 'Solution Landscape',
    explanation:
      'Visualize the full solution space and how your GFlowNet explores it.\n\n' +
      'For molecules: 2D embedding (UMAP/tSNE/PCA) of molecular fingerprints — nearby points are structurally similar. ' +
      'Clusters reveal structural families discovered by the GFlowNet.\n\n' +
      'For grid worlds: reward distribution heatmap overlaid with the empirical sampling distribution — shows whether P(x) ∝ R(x).',
    tips: [
      'Molecules: UMAP preserves global structure; t-SNE emphasizes local clusters',
      'Grid: matching colors between empirical and target = good training',
      'Dense clusters in molecule space may indicate mode collapse',
      'Toggle density overlay to see sampling concentration',
    ],
  },
  interpret: {
    title: 'Model Interpretability',
    explanation:
      'Understand why your GFlowNet generates specific solutions.\n\n' +
      '• Attribution maps — Gradient saliency showing which features drive reward\n' +
      '• Action probabilities — Per-step generation probability distributions\n' +
      '• Reward decomposition — Contribution of each scoring component\n' +
      '• Generation trace — Step-by-step construction process visualization',
    tips: [
      'Select a high-reward candidate first, then explore attribution maps',
      'Generation trace reveals the construction order and decision points',
      'Reward decomposition shows which component drives the total score',
      'Compare attributions across high vs. low reward candidates',
    ],
  },
  flow: {
    title: 'Flow Field Visualization',
    explanation:
      'Visualize the learned flow network as a vector field over the state space.\n\n' +
      'Arrows show the direction and magnitude of probability flow at each state. ' +
      'Flow should converge toward high-reward regions. This directly shows what the GFlowNet has learned.\n\n' +
      'Relevant for all domains, but most intuitive in 2D (grid world).',
    tips: [
      'Strong flow toward reward peaks indicates good learning',
      'Divergent or chaotic flow may indicate underfitting',
      'Compare with the landscape view to see flow-distribution consistency',
      'Flow balance violations highlight where the model still struggles',
    ],
  },
}

const WORKFLOW_STEPS = [
  { step: 1, label: 'Formulate', desc: 'Define state space, actions, reward function', views: ['home', 'formulate'] },
  { step: 2, label: 'Configure', desc: 'Set domain parameters and training hyperparameters', views: ['configure'] },
  { step: 3, label: 'Train', desc: 'Run GFlowNet training and monitor convergence', views: ['train'] },
  { step: 4, label: 'Explore', desc: 'Browse candidates, inspect structures, map landscape', views: ['candidates', 'structure', 'landscape'] },
  { step: 5, label: 'Understand', desc: 'Interpret model decisions, analyze flow', views: ['interpret', 'flow'] },
]

export function AIAssistant({ activeView, problemConfig }: AIAssistantProps) {
  const [open, setOpen] = useState(false)
  const [tab, setTab] = useState<'help' | 'workflow'>('help')

  const help = VIEW_HELP[activeView] || VIEW_HELP.home

  return (
    <>
      {/* Floating Button */}
      <motion.button
        onClick={() => setOpen(!open)}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        className={`fixed bottom-16 right-6 z-50 w-12 h-12 rounded-full shadow-lg flex items-center justify-center transition-colors ${
          open
            ? 'bg-neon-purple text-white shadow-neon-purple/30'
            : 'bg-dark-panel border border-dark-border text-muted-foreground hover:text-white hover:border-neon-purple/50'
        }`}
        title="AI Assistant — contextual help"
      >
        {open ? <X className="w-5 h-5" /> : <Bot className="w-5 h-5" />}
      </motion.button>

      {/* Panel */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0, x: 20, scale: 0.95 }}
            animate={{ opacity: 1, x: 0, scale: 1 }}
            exit={{ opacity: 0, x: 20, scale: 0.95 }}
            transition={{ duration: 0.2 }}
            className="fixed bottom-32 right-6 z-50 w-96 max-h-[70vh] glass-dark rounded-xl border border-neon-purple/30 shadow-2xl shadow-neon-purple/10 flex flex-col overflow-hidden"
          >
            {/* Header */}
            <div className="px-4 py-3 border-b border-dark-border/50 flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-neon-purple to-neon-blue flex items-center justify-center">
                <Bot className="w-4 h-4 text-white" />
              </div>
              <div className="flex-1">
                <h3 className="text-xs font-semibold">GFlowNet Assistant</h3>
                <p className="text-[9px] text-muted-foreground">Context-aware guidance</p>
              </div>

              {/* Tabs */}
              <div className="flex rounded-md border border-dark-border overflow-hidden">
                <button
                  onClick={() => setTab('help')}
                  className={`px-2 py-1 text-[9px] font-medium ${tab === 'help' ? 'bg-neon-purple/20 text-neon-purple' : 'text-muted-foreground'}`}
                >
                  <HelpCircle className="w-3 h-3 inline mr-0.5" />
                  This View
                </button>
                <button
                  onClick={() => setTab('workflow')}
                  className={`px-2 py-1 text-[9px] font-medium ${tab === 'workflow' ? 'bg-neon-purple/20 text-neon-purple' : 'text-muted-foreground'}`}
                >
                  <Workflow className="w-3 h-3 inline mr-0.5" />
                  Workflow
                </button>
              </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto scrollbar-thin p-4 space-y-3">
              {tab === 'help' ? (
                <>
                  {/* View Title */}
                  <h4 className="text-sm font-semibold text-white">{help.title}</h4>

                  {/* Domain Badge */}
                  {problemConfig?.domain_type && (
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 text-[9px] font-medium rounded-full bg-neon-green/15 text-neon-green">
                        {problemConfig.domain_type === 'molecule' ? 'Molecular' :
                         problemConfig.domain_type === 'grid_world' ? 'Grid World' :
                         problemConfig.domain_type === 'dag' ? 'DAG' :
                         problemConfig.domain_type === 'sequence' ? 'Sequence' :
                         problemConfig.domain_type}
                      </span>
                      {problemConfig.training_objective && (
                        <span className="px-2 py-0.5 text-[9px] font-medium rounded-full bg-neon-purple/15 text-neon-purple">
                          {problemConfig.training_objective.replace(/_/g, ' ')}
                        </span>
                      )}
                    </div>
                  )}

                  {/* Explanation */}
                  <div className="text-[11px] text-muted-foreground leading-relaxed whitespace-pre-line">
                    {help.explanation}
                  </div>

                  {/* Tips */}
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-1.5 text-[10px] font-medium text-neon-orange">
                      <Lightbulb className="w-3 h-3" />
                      Tips
                    </div>
                    {help.tips.map((tip, i) => (
                      <div key={i} className="flex items-start gap-2 text-[10px] text-muted-foreground">
                        <span className="text-neon-purple mt-0.5">•</span>
                        <span>{tip}</span>
                      </div>
                    ))}
                  </div>

                  {/* Next Step */}
                  {help.nextStep && (
                    <div className="pt-2 border-t border-dark-border/30">
                      <div className="flex items-center gap-2 text-[10px] text-neon-blue">
                        <ArrowRight className="w-3 h-3" />
                        <span>{help.nextStep.label}</span>
                      </div>
                    </div>
                  )}
                </>
              ) : (
                <>
                  <h4 className="text-sm font-semibold text-white">GFlowNet Optimization Workflow</h4>
                  <p className="text-[10px] text-muted-foreground leading-relaxed">
                    The GFlowNet framework follows a structured workflow — applicable to any domain.
                  </p>

                  <div className="space-y-2">
                    {WORKFLOW_STEPS.map((ws) => {
                      const isCurrent = ws.views.includes(activeView)
                      return (
                        <div
                          key={ws.step}
                          className={`flex items-start gap-3 p-2 rounded-lg transition-colors ${
                            isCurrent ? 'bg-neon-purple/10 border border-neon-purple/30' : 'bg-white/5'
                          }`}
                        >
                          <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 text-[10px] font-bold ${
                            isCurrent ? 'bg-neon-purple text-white' : 'bg-dark-border text-muted-foreground'
                          }`}>
                            {ws.step}
                          </div>
                          <div>
                            <span className={`text-[11px] font-medium ${isCurrent ? 'text-white' : 'text-muted-foreground'}`}>
                              {ws.label}
                            </span>
                            <p className="text-[9px] text-muted-foreground/70">{ws.desc}</p>
                          </div>
                        </div>
                      )
                    })}
                  </div>

                  <div className="pt-2 border-t border-dark-border/30 text-[10px] text-muted-foreground/60">
                    GFlowNet samples objects proportional to R(x), producing a diverse set of high-quality candidates
                    rather than a single optimum — this works across any domain with discrete construction steps.
                  </div>
                </>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}
